main : main.cpp LinkedList.o listiterator.o  listiterator.h  LinkedList.h 
c++ main.cpp -o main LinkedList.o listiterator.o  -std=c++11

LinkedList.o listiterator.o : LinkedList.cpp
c++ LinkedList.cpp listiterator.cpp  -c -std=c++11