main : main.cpp  Audio.o bild.o medium.o 
	c++ main.cpp -o main  Audio.o bild.o medium.o -std=c++11

Audio.o :Audio.cpp
	c++ -c Audio.cpp 

bild.o : bild.cpp
	c++ -c bild.cpp

medium.o :medium.cpp
	c++ -c medium.cpp

